# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.3
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Hexfuncs adds pure multivariate function iotas to hexcasting
display_name: Hexfuncs
github_repo: hexfuncs
github_user: sky3n3t
java_package: mc.sky3n3t.hexfuncs
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 0.1.0
modid: hexfuncs
